=== ccwiechmann/toccer-backend/src/main/resources/inputSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.ccw.io/toccer-backend/inputSchema"
	xmlns:tns="http://www.ccw.io/toccer-backend/inputSchema"
	elementFormDefault="qualified">

	<complexType name="xpath">
		<sequence>
			<element name="expressionWithReplaces" type="string"
				minOccurs="0" />
			<element name="strategy" type="tns:strategy" />
			<element name="cachedXpathResult"
				type="tns:cachedXpathResult" minOccurs="0" />
			<element name="next" type="tns:xpath" minOccurs="0" />
		</sequence>
	</complexType>

	<complexType name="cachedXpathResult">
		<sequence>
			<element name="name" type="string" />
			<element name="xpath" type="string" />
		</sequence>
	</complexType>

	<complexType name="strategy" abstract="true">
		<sequence>
			<element name="json" type="boolean" minOccurs="0" />
			<element name="post" type="boolean" minOccurs="0" />
			<element name="postContent" type="string" minOccurs="0" />
			<element name="headers" type="string" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="numberStrategy">
		<complexContent>
			<extension base="tns:strategy">
				<sequence>
					<element name="from" type="int" />
					<element name="to" type="int" />
					<element name="fillWithPrefixedZerosToLength" type="int"
						minOccurs="0" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="countStrategy">
		<complexContent>
			<extension base="tns:strategy">
				<sequence>
					<element name="xpath" type="string" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="fixedPostUrlStrategy">
		<complexContent>
			<extension base="tns:strategy">
				<sequence>
					<element name="fixedUrls" maxOccurs="unbounded">
						<complexType>
							<sequence>
								<element name="url" type="string" />
							</sequence>
						</complexType>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="multiDataOnOnePageCountStrategy">
		<complexContent>
			<extension base="tns:strategy">
				<sequence>
					<element name="maxXpath" type="string" />
					<element name="categoryForEachEntry" type="boolean"
						minOccurs="0" />
					<element name="titleForEachEntry" type="boolean"
						minOccurs="0" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="ManualCategoryReplacement">
		<sequence>
			<element name="categoryName" type="string" />
			<choice>
				<element name="ifTitleContains" type="string" />
				<element name="ifVolumeIs" type="string" />
			</choice>
		</sequence>
	</complexType>

	<complexType name="ManualVolumeReplacement">
		<sequence>
			<element name="VolumeName" type="string" />
			<element name="ifVolumeEquals" type="string" />
		</sequence>
	</complexType>

	<complexType name="xPathExpression">
		<simpleContent>
			<extension base="string">
				<attribute name="onlyHandleAsReplacement" type="boolean"
					default="false" use="optional" />
			</extension>
		</simpleContent>
	</complexType>

	<element name="inputSchema">
		<complexType>
			<sequence>
				<element name="xpath" type="tns:xpath" />
				<element name="titleXpath" type="tns:xPathExpression" />
				<element name="authorXpath" type="tns:xPathExpression" />
				<element name="pageXpath" type="tns:xPathExpression"
					minOccurs="0" />
				<element name="volumeXpath" type="tns:xPathExpression"
					minOccurs="0" />
				<element name="categoryXpath" type="tns:xPathExpression" />
				<element name="startingHtmlPage" type="string" minOccurs="0" />
				<element name="baseUrl" type="string" />
				<element name="labelNameOfPublication" type="string" />
				<element name="labelToc" type="string" />
				<element name="labelIssuePage" type="string" />
				<element name="urlSuffix" type="string" minOccurs="0" />
				<element name="sortCategories" type="boolean" minOccurs="0" />
				<element name="emptyCategoryReplacements" minOccurs="0">
					<complexType>
						<sequence>
							<element name="fallbackCategoryName" type="string"
								minOccurs="0" />
							<element name="manualCategoryReplacement"
								type="tns:ManualCategoryReplacement" minOccurs="0"
								maxOccurs="unbounded" />
						</sequence>
					</complexType>
				</element>
				<element name="manualVolumeReplacement"
					type="tns:ManualVolumeReplacement" minOccurs="0"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
</schema>

=== ccwiechmann/toccer-backend/src/main/resources/config/elektor.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:inputSchema xmlns:tns="http://www.example.org/inputSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/inputSchema inputSchema.xsd ">
	<tns:xpath>
		<tns:expressionWithReplaces>normalize-space(string-join((//html:div[contains(@class, 'calendar')]/html:table//html:tr[3]//html:a/@href)[{0}], ''))</tns:expressionWithReplaces>
		<tns:countStrategy>
			<tns:xpath>count(//html:div[contains(@class, 'calendar')]/html:table//html:tr[3]//html:a/@href)</tns:xpath>
		</tns:countStrategy>
		<tns:next>
			<tns:expressionWithReplaces>normalize-space(string-join((//html:div[contains(@class, 'issue')]/html:div[@class='box white shadow']/html:div[not(@class)]/html:ul//html:a/@href)[{0}], ''))</tns:expressionWithReplaces>
			<tns:countStrategy>
				<tns:xpath>count(//html:div[contains(@class, 'issue')]/html:div[@class='box white shadow']/html:div[not(@class)]/html:ul//html:a/@href)</tns:xpath>
			</tns:countStrategy>
		</tns:next>
	</tns:xpath>

	<tns:titleXpath>concat(substring(normalize-space(string-join(//html:h1[@itemprop='headline'], '')), 1, number(string-length(normalize-space(string-join(//html:h2[@itemprop='alternativeHeadline'], ''))) = 0)      * string-length(normalize-space(string-join(//html:h1[@itemprop='headline'], '')))), substring(concat(normalize-space(string-join(//html:h1[@itemprop='headline'], '')), ' - ', normalize-space(string-join(//html:h2[@itemprop='alternativeHeadline'], ''))), 1, number(not(string-length(normalize-space(string-join(//html:h2[@itemprop='alternativeHeadline'], ''))) = 0)) * string-length(concat(normalize-space(string-join(//html:h1[@itemprop='headline'], '')), ' - ', normalize-space(string-join(//html:h2[@itemprop='alternativeHeadline'], ''))))))</tns:titleXpath>
	<tns:authorXpath>normalize-space(string-join(//html:li[@itemprop='author']/html:a/html:span[@itemprop='name'], ''))</tns:authorXpath>
	<tns:pageXpath>normalize-space(substring-after(string-join(//html:div[@class='info']/html:ul/html:li[last()], ''), 'Seite '))</tns:pageXpath>
	<tns:volumeXpath>normalize-space(substring-before(substring-after(string-join(//html:div[@class='info']/html:ul/html:li[last()], ''), 'Heft'), '/2018'))</tns:volumeXpath>
	<tns:categoryXpath>normalize-space(string-join(//html:li[@class='category'], ''))</tns:categoryXpath>

	<tns:startingHtmlPage>https://www.elektormagazine.de/magazine</tns:startingHtmlPage>
	<tns:baseUrl></tns:baseUrl>
	<tns:sortCategories>true</tns:sortCategories>
	
	<tns:emptyCategoryReplacements>
		<tns:fallbackCategoryName>EDUCATION &amp; INFORMATION</tns:fallbackCategoryName>
		<tns:manualCategoryReplacement>
			<tns:categoryName>Verschiedenes</tns:categoryName>
			<tns:ifTitleContains>DESIGN</tns:ifTitleContains>
		</tns:manualCategoryReplacement>
		<tns:manualCategoryReplacement>
			<tns:categoryName>Verschiedenes</tns:categoryName>
			<tns:ifTitleContains>SHARE</tns:ifTitleContains>
		</tns:manualCategoryReplacement>
		<tns:manualCategoryReplacement>
			<tns:categoryName>Verschiedenes</tns:categoryName>
			<tns:ifTitleContains>LEARN</tns:ifTitleContains>
		</tns:manualCategoryReplacement>
	</tns:emptyCategoryReplacements>
	
	<tns:manualVolumeReplacement>
		<tns:VolumeName>Jan/Feb</tns:VolumeName>
		<tns:ifVolumeEquals>1</tns:ifVolumeEquals>
	</tns:manualVolumeReplacement>
	<tns:manualVolumeReplacement>
		<tns:VolumeName>B1</tns:VolumeName>
		<tns:ifVolumeEquals>2</tns:ifVolumeEquals>
	</tns:manualVolumeReplacement>
		<tns:manualVolumeReplacement>
		<tns:VolumeName>Mrz/Apr</tns:VolumeName>
		<tns:ifVolumeEquals>3</tns:ifVolumeEquals>
	</tns:manualVolumeReplacement>
	<tns:manualVolumeReplacement>
		<tns:VolumeName>B2</tns:VolumeName>
		<tns:ifVolumeEquals>4</tns:ifVolumeEquals>
	</tns:manualVolumeReplacement>
		<tns:manualVolumeReplacement>
		<tns:VolumeName>Mai/Jun</tns:VolumeName>
		<tns:ifVolumeEquals>5</tns:ifVolumeEquals>
	</tns:manualVolumeReplacement>
	<tns:manualVolumeReplacement>
		<tns:VolumeName>B3</tns:VolumeName>
		<tns:ifVolumeEquals>6</tns:ifVolumeEquals>
	</tns:manualVolumeReplacement>
		<tns:manualVolumeReplacement>
		<tns:VolumeName>Jul/Aug</tns:VolumeName>
		<tns:ifVolumeEquals>7</tns:ifVolumeEquals>
	</tns:manualVolumeReplacement>
	<tns:manualVolumeReplacement>
		<tns:VolumeName>B4</tns:VolumeName>
		<tns:ifVolumeEquals>8</tns:ifVolumeEquals>
	</tns:manualVolumeReplacement>
		<tns:manualVolumeReplacement>
		<tns:VolumeName>Sep/Okt</tns:VolumeName>
		<tns:ifVolumeEquals>9</tns:ifVolumeEquals>
	</tns:manualVolumeReplacement>
	<tns:manualVolumeReplacement>
		<tns:VolumeName>B5</tns:VolumeName>
		<tns:ifVolumeEquals>10</tns:ifVolumeEquals>
	</tns:manualVolumeReplacement>
		<tns:manualVolumeReplacement>
		<tns:VolumeName>Nov/Dez</tns:VolumeName>
		<tns:ifVolumeEquals>11</tns:ifVolumeEquals>
	</tns:manualVolumeReplacement>
	<tns:manualVolumeReplacement>
		<tns:VolumeName>B6</tns:VolumeName>
		<tns:ifVolumeEquals>12</tns:ifVolumeEquals>
	</tns:manualVolumeReplacement>
</tns:inputSchema>

=== ccwiechmann/toccer-backend/src/main/resources/config/informatikSpektrum.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:inputSchema xmlns:tns="http://www.example.org/inputSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/inputSchema inputSchema.xsd ">
	<tns:xpath>
		<tns:expressionWithReplaces>id('volume41')//html:li[{0}]/html:a/@href</tns:expressionWithReplaces>
		<tns:numberStrategy>
			<tns:from>1</tns:from>
			<tns:to>6</tns:to>
		</tns:numberStrategy>
		<tns:next>
			<tns:expressionWithReplaces>id('kb-nav--main')/html:div[3]/html:ol/html:li[{0}]/html:div/html:h3/html:a/@href</tns:expressionWithReplaces>
			<tns:countStrategy>
				<tns:xpath>count(id('kb-nav--main')/html:div[3]/html:ol/html:li)</tns:xpath>
			</tns:countStrategy>
		</tns:next>
	</tns:xpath>

	<tns:titleXpath>//*[@class="ArticleTitle"]</tns:titleXpath>
	<tns:authorXpath>string-join(//html:span[@class="authors__name"]/text(), ', ')</tns:authorXpath>
	<tns:pageXpath>substring-before(substring(//html:span[@class="ArticleCitation_Pages"]/text(), 4), 'â€“')</tns:pageXpath>
	<tns:volumeXpath>substring(//*[@class="ArticleCitation_Issue"]/text(), 7)</tns:volumeXpath>
	<tns:categoryXpath>substring-before(concat(//html:span[@class="test-render-category"]/text(), ' '), ' ')</tns:categoryXpath>

	<tns:startingHtmlPage>https://link.springer.com/journal/volumesAndIssues/287</tns:startingHtmlPage>
	<tns:baseUrl>https://link.springer.com</tns:baseUrl>
	<tns:sortCategories>true</tns:sortCategories>
</tns:inputSchema>

=== ccwiechmann/toccer-backend/src/main/resources/config/ieeeComputer.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:inputSchema
	xmlns:tns="http://www.ccw.io/toccer-backend/inputSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ccw.io/toccer-backend/inputSchema ../inputSchema.xsd ">
	<tns:xpath>
		<tns:strategy xsi:type="tns:fixedPostUrlStrategy">
			<tns:json>true</tns:json>
			<tns:post>true</tns:post>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "8960916", "punumber": "2", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/2/issue/8960916/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "8996090", "punumber": "2", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/2/issue/8996090/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "9034209", "punumber": "2", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/2/issue/9034209/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "9062349", "punumber": "2", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/2/issue/9062349/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "9089073", "punumber": "2", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/2/issue/9089073/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "9107270", "punumber": "2", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/2/issue/9107270/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "9130391", "punumber": "2", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/2/issue/9130391/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "9153282", "punumber": "2", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/2/issue/9153282/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "9187448", "punumber": "2", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/2/issue/9187448/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "9206399", "punumber": "2", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/2/issue/9206399/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "9237328", "punumber": "2", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/2/issue/9237328/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "9269873", "punumber": "2", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/2/issue/9269873/toc</tns:url>
			</tns:fixedUrls>
		</tns:strategy>
		<tns:next>
			<tns:strategy xsi:type="tns:multiDataOnOnePageCountStrategy">
				<tns:maxXpath>count(//html:div[@class="records"]/html:div[@class="json_object"])</tns:maxXpath>
				<tns:categoryForEachEntry>true</tns:categoryForEachEntry>
			</tns:strategy>
		</tns:next>
	</tns:xpath>

	<tns:titleXpath>normalize-space(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="articleTitle"]/text())</tns:titleXpath>
	<tns:authorXpath>string-join(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="authors"]//html:div[@class="preferredName"]/text(), ', ')</tns:authorXpath>
	<tns:pageXpath>normalize-space(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="startPage"]/text())</tns:pageXpath>
	
	<tns:volumeXpath>normalize-space(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="issue"]/text())</tns:volumeXpath>
	<tns:categoryXpath>normalize-space(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="subjectCategories"]/text())</tns:categoryXpath>
	<tns:baseUrl>https://ieeexplore.ieee.org</tns:baseUrl>
	<tns:labelNameOfPublication>IEEE Computer, Volume 53</tns:labelNameOfPublication>
	<tns:labelToc>Table of Contents</tns:labelToc>
	<tns:labelIssuePage>Issue, Page</tns:labelIssuePage>
	<tns:sortCategories>true</tns:sortCategories>
</tns:inputSchema>
