=== ccwiechmann/toccer-backend/src/main/resources/inputSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.ccw.io/toccer-backend/inputSchema"
	xmlns:tns="http://www.ccw.io/toccer-backend/inputSchema"
	elementFormDefault="qualified">

	<complexType name="xpath">
		<sequence>
			<element name="expressionWithReplaces" type="string"
				minOccurs="0" />
			<element name="strategy" type="tns:strategy" />
			<element name="cachedXpathResult"
				type="tns:cachedXpathResult" minOccurs="0" />
			<element name="next" type="tns:xpath" minOccurs="0" />
		</sequence>
	</complexType>

	<complexType name="cachedXpathResult">
		<sequence>
			<element name="name" type="string" />
			<element name="xpath" type="string" />
		</sequence>
	</complexType>

	<complexType name="strategy" abstract="true">
		<sequence>
			<element name="json" type="boolean" minOccurs="0" />
			<element name="post" type="boolean" minOccurs="0" />
			<element name="postContent" type="string" minOccurs="0" />
			<element name="headers" type="string" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="numberStrategy">
		<complexContent>
			<extension base="tns:strategy">
				<sequence>
					<element name="from" type="int" />
					<element name="to" type="int" />
					<element name="fillWithPrefixedZerosToLength" type="int"
						minOccurs="0" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="countStrategy">
		<complexContent>
			<extension base="tns:strategy">
				<sequence>
					<element name="xpath" type="string" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="fixedPostUrlStrategy">
		<complexContent>
			<extension base="tns:strategy">
				<sequence>
					<element name="fixedUrls" maxOccurs="unbounded">
						<complexType>
							<sequence>
								<element name="url" type="string" />
							</sequence>
						</complexType>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="multiDataOnOnePageCountStrategy">
		<complexContent>
			<extension base="tns:strategy">
				<sequence>
					<element name="maxXpath" type="string" />
					<element name="categoryForEachEntry" type="boolean"
						minOccurs="0" />
					<element name="titleForEachEntry" type="boolean"
						minOccurs="0" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="ManualCategoryReplacement">
		<sequence>
			<element name="categoryName" type="string" />
			<choice>
				<element name="ifTitleContains" type="string" />
				<element name="ifVolumeIs" type="string" />
			</choice>
		</sequence>
	</complexType>

	<complexType name="ManualVolumeReplacement">
		<sequence>
			<element name="VolumeName" type="string" />
			<element name="ifVolumeEquals" type="string" />
		</sequence>
	</complexType>

	<complexType name="xPathExpression">
		<simpleContent>
			<extension base="string">
				<attribute name="onlyHandleAsReplacement" type="boolean"
					default="false" use="optional" />
			</extension>
		</simpleContent>
	</complexType>

	<element name="inputSchema">
		<complexType>
			<sequence>
				<element name="xpath" type="tns:xpath" />
				<element name="titleXpath" type="tns:xPathExpression" />
				<element name="authorXpath" type="tns:xPathExpression" />
				<element name="pageXpath" type="tns:xPathExpression"
					minOccurs="0" />
				<element name="volumeXpath" type="tns:xPathExpression"
					minOccurs="0" />
				<element name="categoryXpath" type="tns:xPathExpression" />
				<element name="startingHtmlPage" type="string" minOccurs="0" />
				<element name="baseUrl" type="string" />
				<element name="labelNameOfPublication" type="string" />
				<element name="labelToc" type="string" />
				<element name="labelIssuePage" type="string" />
				<element name="urlSuffix" type="string" minOccurs="0" />
				<element name="sortCategories" type="boolean" minOccurs="0" />
				<element name="emptyCategoryReplacements" minOccurs="0">
					<complexType>
						<sequence>
							<element name="fallbackCategoryName" type="string"
								minOccurs="0" />
							<element name="manualCategoryReplacement"
								type="tns:ManualCategoryReplacement" minOccurs="0"
								maxOccurs="unbounded" />
						</sequence>
					</complexType>
				</element>
				<element name="manualVolumeReplacement"
					type="tns:ManualVolumeReplacement" minOccurs="0"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
</schema>

=== ccwiechmann/toccer-backend/src/main/resources/config/itInformationTechnology.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:inputSchema
	xmlns:tns="http://www.ccw.io/toccer-backend/inputSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ccw.io/toccer-backend/inputSchema ../inputSchema.xsd ">
	<tns:xpath>
		<tns:expressionWithReplaces>//html:ul[@id="expandVolume-65"]//html:a[{0}]/@href</tns:expressionWithReplaces>
		<tns:strategy xsi:type="tns:countStrategy">
			<tns:xpath>count(//html:ul[@id="expandVolume-65"]//html:a)</tns:xpath>
		</tns:strategy>
		<tns:next>
			<tns:strategy xsi:type="tns:multiDataOnOnePageCountStrategy">
				<tns:maxXpath>count(//html:div[contains(@class, 'searchResultContent')])</tns:maxXpath>
				<tns:categoryForEachEntry>true</tns:categoryForEachEntry>
				<tns:titleForEachEntry>false</tns:titleForEachEntry>
			</tns:strategy>
		</tns:next>
	</tns:xpath>

	<tns:titleXpath>//html:div[contains(@class, 'searchResultContent')]//html:h4[contains(@class, 'titleSearchPageResult')]</tns:titleXpath>
	<tns:authorXpath>normalize-space((//html:div[contains(@class, 'searchResultContent')])[{0}]//html:div[contains(@class, 'contributors')])</tns:authorXpath>
	<tns:pageXpath>substring-before(substring-after((//html:div[contains(@class, 'searchResultContent')])[{0}]//html:span[contains(@class, 'pageRange')], 'Page range: '), '-')</tns:pageXpath>
	<tns:volumeXpath>substring-before(substring-after(//html:h1, 'Issue '), ' - ')</tns:volumeXpath>
	<tns:categoryXpath>normalize-space((//html:div[contains(@class, 'searchResultContent')])[{0}]/../../../../html:h3)</tns:categoryXpath>

	<tns:startingHtmlPage>https://www.degruyter.com/view/j/itit</tns:startingHtmlPage>
	<tns:baseUrl>https://www.degruyter.com</tns:baseUrl>
	<tns:labelNameOfPublication>it â€“ Information Technology, Volume 65</tns:labelNameOfPublication>
	<tns:labelToc>Table of Contents</tns:labelToc>
	<tns:labelIssuePage>Issue, Page</tns:labelIssuePage>
	<tns:sortCategories>false</tns:sortCategories>
	<tns:emptyCategoryReplacements>
		<tns:fallbackCategoryName>FRONTMATTER</tns:fallbackCategoryName>
	</tns:emptyCategoryReplacements>
</tns:inputSchema>

=== ccwiechmann/toccer-backend/src/main/resources/config/ieeeSoftware.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:inputSchema xmlns:tns="http://www.example.org/inputSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/inputSchema inputSchema.xsd ">
	<tns:xpath>
		<tns:fixedPostUrlStrategy>
			<tns:json>true</tns:json>
			<tns:post>true</tns:post>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "8239922", "punumber": "52", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/52/issue/8239922/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "8314148", "punumber": "52", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/52/issue/8314148/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "8354413", "punumber": "52", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/52/issue/8354413/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "8405616", "punumber": "52", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/52/issue/8405616/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "8474478", "punumber": "52", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/52/issue/8474478/toc</tns:url>
			</tns:fixedUrls>
			<tns:fixedUrls>
				<tns:headers>Host: ieeexplore.ieee.org</tns:headers>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:content>{"isnumber": "8552618", "punumber": "52", "sortType": "vol-only-seq", "rowsPerPage": "50"}</tns:content>
				<tns:url>https://ieeexplore.ieee.org/rest/search/pub/52/issue/8552618/toc</tns:url>
			</tns:fixedUrls>
		</tns:fixedPostUrlStrategy>
		<tns:next>
			<tns:multiDataOnOnePageCountStrategy>
				<tns:maxXpath>count(//html:div[@class="records"]/html:div[@class="json_object"])</tns:maxXpath>
				<tns:categoryForEachEntry>true</tns:categoryForEachEntry>
			</tns:multiDataOnOnePageCountStrategy>
		</tns:next>
	</tns:xpath>

	<tns:titleXpath>normalize-space(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="articleTitle"]/text())</tns:titleXpath>
	<tns:authorXpath>string-join(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="authors"]//html:div[@class="preferredName"]/text(), ', ')</tns:authorXpath>
	<tns:pageXpath>normalize-space(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="startPage"]/text())</tns:pageXpath>
	
	<tns:volumeXpath>normalize-space(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="issue"]/text())</tns:volumeXpath>
	<tns:categoryXpath>normalize-space(//idonotexist/text())</tns:categoryXpath>
	<tns:baseUrl>https://ieeexplore.ieee.org</tns:baseUrl>
	<tns:sortCategories>false</tns:sortCategories>
	
	<tns:emptyCategoryReplacements>
		<tns:fallbackCategoryName>ERROR</tns:fallbackCategoryName>
		<tns:manualCategoryReplacement>
			<tns:categoryName>SAFETY AND SECURITY IN CYBER-PHYSICAL SYSTEMS</tns:categoryName>
			<tns:ifVolumeIs>1</tns:ifVolumeIs>
		</tns:manualCategoryReplacement>
		<tns:manualCategoryReplacement>
			<tns:categoryName>RELEASE ENGINEERING 3.0</tns:categoryName>
			<tns:ifVolumeIs>2</tns:ifVolumeIs>
		</tns:manualCategoryReplacement>
		<tns:manualCategoryReplacement>
			<tns:categoryName>MICROSERVICES</tns:categoryName>
			<tns:ifVolumeIs>3</tns:ifVolumeIs>
		</tns:manualCategoryReplacement>
		<tns:manualCategoryReplacement>
			<tns:categoryName>PROCESS IMPROVEMENT</tns:categoryName>
			<tns:ifVolumeIs>4</tns:ifVolumeIs>
		</tns:manualCategoryReplacement>
		<tns:manualCategoryReplacement>
			<tns:categoryName>SOFTWARE ENGINEERING'S 50TH ANNIVERSARY</tns:categoryName>
			<tns:ifVolumeIs>5</tns:ifVolumeIs>
		</tns:manualCategoryReplacement>
		<tns:manualCategoryReplacement>
			<tns:categoryName>COLLABORATIVE MODELING IN SOFTWARE ENGINEERING</tns:categoryName>
			<tns:ifVolumeIs>6</tns:ifVolumeIs>
		</tns:manualCategoryReplacement>
	</tns:emptyCategoryReplacements>
</tns:inputSchema>

=== ccwiechmann/toccer-backend/src/main/resources/config/softwaretechnikTrends.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<tns:inputSchema
	xmlns:tns="http://www.ccw.io/toccer-backend/inputSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ccw.io/toccer-backend/inputSchema ../inputSchema.xsd ">
	<tns:xpath>
		<tns:expressionWithReplaces>'band/band-43-heft-{0}'</tns:expressionWithReplaces>
		<tns:strategy xsi:type="tns:numberStrategy">
			<tns:from>1</tns:from>
			<tns:to>4</tns:to>
		</tns:strategy>
		<tns:next>
			<tns:strategy xsi:type="tns:multiDataOnOnePageCountStrategy">
				<tns:maxXpath>count((//html:a[contains(@href, '.pdf')]/parent::*))</tns:maxXpath>
				<tns:categoryForEachEntry>true</tns:categoryForEachEntry>
				<tns:titleForEachEntry>true</tns:titleForEachEntry>
			</tns:strategy>
		</tns:next>
	</tns:xpath>

	<tns:titleXpath>normalize-space(string-join(tokenize((  //html:a[contains(@href, '.pdf')]/parent::*)[{0}]/text()[1]   , 'S\.')[position()&lt;last()], 'S.'))</tns:titleXpath>
	<tns:authorXpath>normalize-space(substring-before((//html:a[contains(@href, '.pdf')])[{0}]/parent::*/text()[1] | (//html:a[contains(@href, '.pdf')])[{0}]/parent::*/text()[1][normalize-space()], ':'))</tns:authorXpath>
	
	<tns:pageXpath>normalize-space(substring-before(concat(substring-before(tokenize((//html:a[contains(@href, '.pdf')]/parent::*)[{0}], 'S\.')[last()], ' PDF'), '-'), '-'))</tns:pageXpath>
	<tns:volumeXpath>normalize-space(substring-after(//html:span[contains(text(), 'Heft')], 'Heft '))</tns:volumeXpath>
	<tns:categoryXpath>normalize-space((//html:a[contains(@href, '.pdf')]/parent::*)[{0}]/text()/ancestor::html:li[html:strong]/html:strong/text())</tns:categoryXpath>
	<tns:startingHtmlPage>https://fb-swt.gi.de/publikationen/softwaretechnik-trends/</tns:startingHtmlPage>
	<tns:baseUrl>https://fb-swt.gi.de/publikationen/softwaretechnik-trends/</tns:baseUrl>
	<tns:labelNameOfPublication>Softwaretechnik-Trends, Band 43</tns:labelNameOfPublication>
	<tns:labelToc>Inhaltsverzeichnis</tns:labelToc>
	<tns:labelIssuePage>Ausgabe, Seite</tns:labelIssuePage>
	<tns:sortCategories>false</tns:sortCategories>
</tns:inputSchema>

=== ccwiechmann/toccer-backend/src/main/resources/config/datenbankSpektrum.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:inputSchema
	xmlns:tns="http://www.ccw.io/toccer-backend/inputSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ccw.io/toccer-backend/inputSchema ../inputSchema.xsd ">
	<tns:xpath>
		<tns:expressionWithReplaces>//html:li[html:h2[html:span[contains(text(), 'Volume 23')]]]/html:ul/html:li[{0}]/html:a/@href</tns:expressionWithReplaces>
		<tns:strategy xsi:type="tns:countStrategy">
			<tns:xpath>count(//html:li[html:h2[html:span[contains(text(), 'Volume 23')]]]/html:ul/html:li)</tns:xpath>
		</tns:strategy>
		<tns:next>
			<tns:expressionWithReplaces>substring-after(//html:li[html:article[contains(@class, 'app-card-open')]][{0}]//html:a/@href, 'https://link.springer.com')</tns:expressionWithReplaces>
			<tns:strategy xsi:type="tns:countStrategy">
				<tns:xpath>count(//html:article[contains(@class, 'app-card-open')])</tns:xpath>
			</tns:strategy>
			<tns:cachedXpathResult>
				<tns:name>issueNumber</tns:name>
				<tns:xpath>substring-after(substring-after(//html:meta[contains(@property, 'og:title')]/@content, ', '), ' ')</tns:xpath>
			</tns:cachedXpathResult>
		</tns:next>
	</tns:xpath>

	<tns:titleXpath>//html:meta[@name="citation_title"]/@content</tns:titleXpath>
	<tns:authorXpath>string-join(//html:meta[@name="dc.creator"]/@content, '; ')</tns:authorXpath>
	<tns:pageXpath>//html:meta[@name="citation_firstpage"]/@content</tns:pageXpath>
	<tns:volumeXpath onlyHandleAsReplacement="true">{issueNumber}</tns:volumeXpath>
	<tns:categoryXpath>//html:meta[@name="citation_article_type"]/@content</tns:categoryXpath>

	<tns:startingHtmlPage>https://link.springer.com/journal/volumesAndIssues/13222</tns:startingHtmlPage>
	<tns:baseUrl>https://link.springer.com</tns:baseUrl>
	<tns:labelNameOfPublication>Datenbank-Spektrum, Band 23</tns:labelNameOfPublication>
	<tns:labelToc>Inhaltsverzeichnis</tns:labelToc>
	<tns:labelIssuePage>Ausgabe, Seite</tns:labelIssuePage>
	<tns:sortCategories>false</tns:sortCategories>
</tns:inputSchema>

=== ccwiechmann/toccer-backend/src/main/resources/config/computerScienceResearchAndDevelopment.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:inputSchema
	xmlns:tns="http://www.ccw.io/toccer-backend/inputSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ccw.io/toccer-backend/inputSchema ../inputSchema.xsd ">
	<tns:xpath>
		<tns:expressionWithReplaces>//html:li[@class='app-section'][contains(., 'Volume 35')]/html:ul/html:li[{0}]/html:a/@href</tns:expressionWithReplaces>
		<tns:strategy xsi:type="tns:countStrategy">
			<tns:xpath>count(//html:li[@class='app-section'][contains(., 'Volume 35')]/html:ul/html:li)</tns:xpath>
		</tns:strategy>
		<tns:next>
			<tns:expressionWithReplaces>substring(//html:ol[contains(@class, 'app-volumes-and-issues__article-list')]/html:li[{0}]//html:a/@href, 26)</tns:expressionWithReplaces>
			<tns:strategy xsi:type="tns:countStrategy">
				<tns:xpath>count(//html:ol[contains(@class, 'app-volumes-and-issues__article-list')]/html:li)</tns:xpath>
			</tns:strategy>
			<tns:cachedXpathResult>
				<tns:name>issueNumber</tns:name>
				<tns:xpath>substring-before(substring-after(//html:div[@class='app-volumes-and-issues__content']/html:div[@class='app-volumes-and-issues__info']/html:h1/text(), 'issue '), ',')</tns:xpath>
			</tns:cachedXpathResult>
		</tns:next>
	</tns:xpath>

	<tns:titleXpath>concat(substring(//*[@data-test='article-title'], 1, number(exists(//html:body[@class='shared-article-renderer'])) * string-length(//*[@data-test='article-title'])), substring(//*[@class="ArticleTitle"], 1, number(not(exists(//html:body[@class='shared-article-renderer']))) * string-length(//*[@class="ArticleTitle"])))</tns:titleXpath>
	<tns:authorXpath>concat(substring(string-join((//*[@data-test="author-name"]/text()), ', '), 1, number(exists(//html:body[@class='shared-article-renderer'])) * string-length(string-join((//*[@data-test="author-name"]/text()), ', '))), substring(string-join(//html:span[@class="authors__name"]/text(), ', '), 1, number(not(exists(//html:body[@class='shared-article-renderer']))) * string-length(string-join(//html:span[@class="authors__name"]/text(), ', '))))</tns:authorXpath>
	<tns:pageXpath>substring-after(substring-before(substring-after(substring-before(//html:p[@class='c-article-info-details'], ' (2020)'), 'page'), 'â€“'), ' ')</tns:pageXpath>
	<tns:volumeXpath onlyHandleAsReplacement="true">{issueNumber}</tns:volumeXpath>
	<tns:categoryXpath>concat(substring(//*[@data-test="article-category"]/text(), 1, number(exists(//html:body[@class='shared-article-renderer'])) * string-length(//*[@data-test="article-category"]/text())), substring(//html:span[@class="test-render-category"]/text(), 1, number(not(exists(//html:body[@class='shared-article-renderer']))) * string-length(//html:span[@class="test-render-category"]/text())))</tns:categoryXpath>

	<tns:startingHtmlPage>https://link.springer.com/journal/volumesAndIssues/450</tns:startingHtmlPage>
	<tns:baseUrl>https://link.springer.com</tns:baseUrl>
	<tns:labelNameOfPublication>Software-Intensive Cyber-Physical Systems, Volume 35</tns:labelNameOfPublication>
	<tns:labelToc>Table of Contents</tns:labelToc>
	<tns:labelIssuePage>Issue, Page</tns:labelIssuePage>
	<tns:sortCategories>false</tns:sortCategories>
</tns:inputSchema>

=== ccwiechmann/toccer-backend/src/main/resources/config/proceedingsOfTheIeee.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:inputSchema
	xmlns:tns="http://www.ccw.io/toccer-backend/inputSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ccw.io/toccer-backend/inputSchema ../inputSchema.xsd ">
	<tns:xpath>
		<tns:expressionWithReplaces>//html:div[contains(@class, 'elementor-widget-wrap')][html:div[html:div[html:h2[contains(text(), '2023')]]]]//html:div[contains(@class, 'trx_addons_column-1_3')][{0}]//html:a[contains(@rel, 'bookmark')]/@href</tns:expressionWithReplaces>
		<tns:strategy xsi:type="tns:countStrategy">
			<tns:xpath>count(//html:div[contains(@class, 'elementor-widget-wrap')][html:div[html:div[html:h2[contains(text(), '2023')]]]]//html:div[contains(@class, 'trx_addons_column-1_3')]//html:a[contains(@rel, 'bookmark')]/@href)</tns:xpath>
		</tns:strategy>
		<tns:next>
			<tns:expressionWithReplaces>concat('https://ieeexplore.ieee.org/rest/search/pub/5/issue/', substring-before(substring-after(//html:section[1]//html:a[contains(@href, 'isnumber')]/@href, 'isnumber='), '&amp;'), '/toc')</tns:expressionWithReplaces>
			<tns:strategy xsi:type="tns:numberStrategy">
				<tns:json>true</tns:json>
				<tns:post>true</tns:post>
				<tns:postContent>concat('{"isnumber":"', substring-before(substring-after(//html:section[1]//html:a[contains(@href, 'isnumber')]/@href, 'isnumber='), '&amp;'), '","punumber":"5","sortType":"vol-only-seq"}')</tns:postContent>
				<tns:headers>Origin: https://ieeexplore.ieee.org</tns:headers>
				<tns:from>1</tns:from>
				<tns:to>1</tns:to>
			</tns:strategy>
			<tns:next>
				<tns:strategy xsi:type="tns:multiDataOnOnePageCountStrategy">
					<tns:maxXpath>count(//html:div[@class="records"]/html:div[@class="json_object"])</tns:maxXpath>
					<tns:categoryForEachEntry>true</tns:categoryForEachEntry>
					<tns:titleForEachEntry>true</tns:titleForEachEntry>
				</tns:strategy>
			</tns:next>
		</tns:next>
	</tns:xpath>

	<tns:titleXpath>normalize-space(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="articleTitle"]/text())</tns:titleXpath>
	<tns:authorXpath>string-join(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="authors"]//html:div[@class="preferredName"]/text(), ', ')</tns:authorXpath>
	<tns:pageXpath>normalize-space(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="startPage"]/text())</tns:pageXpath>
	<tns:volumeXpath>normalize-space(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="issue"]/text())</tns:volumeXpath>
	<tns:categoryXpath>normalize-space(//html:div[@class="records"]/html:div[@class="json_object"][{0}]/html:div[@class="subjectCategories"]/text())</tns:categoryXpath>

	<tns:startingHtmlPage>https://proceedingsoftheieee.ieee.org/journal/past-issues/</tns:startingHtmlPage>
	<tns:baseUrl />
	<tns:labelNameOfPublication>Proceedings of the IEEE, Volume 111</tns:labelNameOfPublication>
	<tns:labelToc>Table of Contents</tns:labelToc>
	<tns:labelIssuePage>Issue, Page</tns:labelIssuePage>
	<tns:sortCategories>false</tns:sortCategories>
</tns:inputSchema>

=== ccwiechmann/toccer-backend/src/main/resources/config/objektSpektrum.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:inputSchema xmlns:tns="http://www.example.org/inputSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/inputSchema inputSchema.xsd ">
	<tns:xpath>
		<tns:expressionWithReplaces>string-join((//figure[@class='module-price-badge' and ./a/img[contains(./@alt, '2017')]]/a/@href)[{0}], '')</tns:expressionWithReplaces>
		<tns:numberStrategy>
			<tns:from>1</tns:from>
			<tns:to>6</tns:to>
		</tns:numberStrategy>
	</tns:xpath>

	<tns:titleXpath>normalize-space(string-join(//html:div[@class='col-sm-9']/html:h1/text(), ''))</tns:titleXpath>
	<tns:authorXpath>normalize-space(string-join(//html:div[@class='col-sm-12']/html:div[@class='content']/html:p[2]/text(), ''))</tns:authorXpath>
	
	<tns:categoryXpath>concat(normalize-space(string-join(substring-after(substring-before(//html:div[@class='issueInfo']/html:p/text()[1], '/2017'), ' - '), '')), ': ', normalize-space(substring-after(string-join(//html:div[@class='issueInfo']/html:p/text(), ''), '2017')))</tns:categoryXpath>
	<tns:startingHtmlPage>https://bc-v3.pressmatrix.com/de/profiles/4967c6d5eae1/editions</tns:startingHtmlPage>
	<tns:baseUrl>https://bc-v3.pressmatrix.com</tns:baseUrl>
	<tns:sortCategories>false</tns:sortCategories>
</tns:inputSchema>

=== ccwiechmann/toccer-backend/src/main/resources/config/javaSpektrum.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:inputSchema xmlns:tns="http://www.example.org/inputSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/inputSchema ../inputSchema.xsd ">
	<tns:xpath>
		<tns:expressionWithReplaces>string-join((//*[@class='module-price-badge' and .//*[contains(./@alt, '2017')]]/html:a/@href)[{0}], '')</tns:expressionWithReplaces>
		<tns:numberStrategy>
			<tns:from>1</tns:from>
			<tns:to>6</tns:to>
		</tns:numberStrategy>
		<tns:next>
			<tns:expressionWithReplaces>concat(string-join(//html:div[@class='col-md-6']/html:a/@href, ''), '/page/3')</tns:expressionWithReplaces>
			<tns:numberStrategy>
				<tns:from>1</tns:from>
				<tns:to>1</tns:to>
			</tns:numberStrategy>
			<tns:next>
				<tns:expressionWithReplaces>string-join((//html:div[@data-name='page']/html:a/@href[contains(., 'de/profiles')])[{0}], '')</tns:expressionWithReplaces>
				<tns:countStrategy>
					<tns:xpath>count(//html:div[@data-name='page']/html:a/@href[contains(., 'de/profiles')])</tns:xpath>
				</tns:countStrategy>
				<tns:next>
					<tns:expressionWithReplaces>string-join((//html:a/@data-url[contains(., 'de/profiles')])[1], '')</tns:expressionWithReplaces>
					<tns:numberStrategy>
						<tns:from>1</tns:from>
						<tns:to>1</tns:to>
					</tns:numberStrategy>
				</tns:next>
			</tns:next>
		</tns:next>
	</tns:xpath>

	<tns:titleXpath>normalize-space(string-join(//html:h1//html:strong, ''))</tns:titleXpath>
	<tns:authorXpath>normalize-space(string-join((//html:h1/following-sibling::html:p/html:strong[./html:br])[1]//text(), ''))</tns:authorXpath>
	
	<tns:categoryXpath>concat('placeholder', '')</tns:categoryXpath>
	<tns:startingHtmlPage>https://bc-v3.pressmatrix.com/de/profiles/4967c6d5eae1/editions</tns:startingHtmlPage>
	<tns:baseUrl>https://bc-v3.pressmatrix.com</tns:baseUrl>
	<tns:sortCategories>false</tns:sortCategories>
</tns:inputSchema>
